// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbTY7fCVsv4HjImC01YPdwy46o7C_Ev4',
    appId: '1:798050347787:web:40afcb11cf4fad271f500e',
    messagingSenderId: '798050347787',
    projectId: 'chatapp-cb66d',
    authDomain: 'chatapp-cb66d.firebaseapp.com',
    storageBucket: 'chatapp-cb66d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ML7yWRsrCWqhPM1O3ecKkAHRaFZffys',
    appId: '1:798050347787:android:e534d357752fbbce1f500e',
    messagingSenderId: '798050347787',
    projectId: 'chatapp-cb66d',
    storageBucket: 'chatapp-cb66d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD18eyXSbB4HBUpFwKfti5sTahpHN9e9Ps',
    appId: '1:798050347787:ios:4f8a26f62f028a521f500e',
    messagingSenderId: '798050347787',
    projectId: 'chatapp-cb66d',
    storageBucket: 'chatapp-cb66d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD18eyXSbB4HBUpFwKfti5sTahpHN9e9Ps',
    appId: '1:798050347787:ios:a474ff327b5eda4a1f500e',
    messagingSenderId: '798050347787',
    projectId: 'chatapp-cb66d',
    storageBucket: 'chatapp-cb66d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
